### ISSUE TITLE
Does the mod support animations with bending?

### ISSUE THREAD

**Issue by WhiseNT** [liopyu/AnimationJS#1]
If so, I want to know how to create a bending model.

**Comment by liopyu** [comment]
it should automatically play bending animations when bendylib is installed as an optional dependency. as for creating bendy animations this is more an Emotecraft question, however theres this page on the [Emotecraft wiki](https://kosmx.gitbook.io/emotecraft/tutorial/custom-emotes) which explains creating animations and also has a default model you can download.

**Comment by liopyu** [comment]
[anim_walk.json](https://github.com/user-attachments/files/17451654/anim_walk.json)
as an example animation there's this emote downloaded from the [Emotecraft Collection](https://emotes.kosmx.dev/e?s=walk) page and converted with their built in emotecraft to json converter which if placed in the `kubejs>assets>animationjs>player_animation>anim_walk.json` folder will be able to be played like so
```javascript
AnimationJS.universalController(event => {
	if (event.player.isShiftKeyDown()) {
		event.startAnimation("animationjs:anim_walk")
	} else {
		event.stopAnimation("animationjs:anim_walk")
	}
})
```
https://github.com/user-attachments/assets/1ce4da8b-f2bd-4027-bc61-45b21848927d

**Comment by WhiseNT** [comment]
There is a strange bug.
If I use oculus,the bendy animations won't be run correctly(it will be a animation without bendy).
maybe I need to ask KosmX for help?
